### ISSUE TITLE
MELPA submission

### ISSUE THREAD

**Issue by progfolio** [amno1/dired-auto-readme#6]
Any interest in finishing this off?

https://github.com/melpa/melpa/pull/8212

Has the bug mentioned in that pull request been fixed?

**Comment by amno1** [comment]
No, I don't think the bug is fixed; I could never trigger it in my Emacs.

I do plan to make other changes and finish it, however for now I believe you can just close my request for MELPA submission. I am not sure when I will have time to work on this. I can give you another request when I am done with it, so you don't have this open. Sorry for the waiting, and thanks for all the help!

**Comment by bezirg** [comment]
I see the package on MELPA; shouldn't this issue be closed?

**Comment by amno1** [comment]
Yes indeed, thank you bezirg for reminding me. I am rarely logged into GH nowadays.
